### ISSUE TITLE
help! sample can't run

### ISSUE THREAD

**Issue by itlwy** [hexhacking/xUnwind#1]
I downloaded the examples on github and can’t run. 
The error message is as follows：
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
prefabUsage: prefab [OPTIONS] [PACKAGE_PATH]...
prefabError: Invalid value for "PACKAGE_PATH": Directory "/Users/lwy/code_workspace/java/xUnwind-master/xunwind/build/intermediates/prefab_package/debug/prefab" is not readable.
executing external native build for cmake /Users/lwy/code_workspace/java/xUnwind-master/xunwind_sample/src/main/cpp/CMakeLists.txt

BUILD SUCCESSFUL in 2s

**Comment by caikelun** [comment]
Thanks for the feedback. This problem has been fixed in the latest commit (https://github.com/hexhacking/xUnwind/commit/a9f921eeebfc5b47c465e6ac97ab738617aa674e#diff-d2072d2b4044593911c5c3e659f1004212e23dff50cf7c34c44a8d6ef46a155e).
