### ISSUE TITLE
BuildId printing is required

### ISSUE THREAD

**Issue by Klayflash** [hexhacking/xUnwind#3]
Hello.

I'm found that the library does not print BuildId like android's crash dumper.

xUnwind example:
```
: #00 pc 001b5548  /data/app/~~e_GE1lEQefY82roFs1FWDA==/com.example.Tests-a19SzXnXizKY4uhToyS7lA==/lib/x86/libmain.so
```

android crush dumper example (contains BuildId at end of a line):
```
12-20 00:03:53.008 11002 11002 F DEBUG   :       #00 pc 001c4af7  /data/app/~~e_GE1lEQefY82roFs1FWDA==/com.example.Tests-a19SzXnXizKY4uhToyS7lA==/lib/x86/libmain.so (BuildId: 1235265346346457347346765467547645865548)
```

readelf dump of symbols:
```
D:\android-ndk-r21b\toolchains\llvm\prebuilt\windows-x86_64\bin\i686-linux-android-readelf.exe -n D:\temp\symbols\x86\libmain.so

Displaying notes found at file offset 0x00000134 with length 0x00000098:
  Owner                 Data size       Description
  Android              0x00000084       NT_VERSION (version)

Displaying notes found at file offset 0x000001cc with length 0x00000024:
  Owner                 Data size       Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 1235265346346457347346765467547645865548

Displaying notes found at file offset 0x08b4a990 with length 0x0000001c:
  Owner                 Data size       Description
  GNU                  0x00000009       NT_GNU_GOLD_VERSION (gold version)
    Version: gold 1.12
```

**Comment by Klayflash** [comment]
BuildId helps match crash with symbols.

If BuildId is not match then ndk-stack will show 
```
WARNING: Mismatched build id for D:\symbols\x86\libmain.so
WARNING:   Expected 1235265346346457347346765467547645865548
WARNING:   Found    1235265346346457347346765467547645860000
```

[BuildId documentation](https://source.android.com/devices/tech/debug/native-crash)

**Comment by caikelun** [comment]
Hi @Klayflash,

xUnwind is a basic library with relatively simple functions. Backtrace can be used in many scenarios, such as crash analysis, performance analysis, business logic analysis, and so on. The build ID is not always required, and in some high-frequency calling scenarios, I think it is not a good idea to append the build ID to each backtrace line every time. If you need it, you can implement the logic of parsing the build ID from ELF in your business code.

Therefore, we will not attach build ID information. Thank you for your suggestion anyway.

**Comment by Klayflash** [comment]
Thanks for answer! I've found getting of build ID in hexhacking/xCrash.

There are two operations visible by me:

- stack capture. It is must be a fast as possible operation as you mentioned. (should gather only addresses for example)
- stack print. It should be customizable operation with optional printing of BuildId.  Fast as possible is not required.

stack capture operation for boost::stacktrace is:
`auto capturedStack = boost::stacktrace::stacktrace();`

and stack print operation for boost::stacktrace is:
`std::string printedStack = boost::stacktrace::to_string(capturedStack)`

which functions from hexhacking I should use for the stack these capture and stack print?

**Comment by Klayflash** [comment]
I've found [build-id](https://github.com/mattst88/build-id) library that can get BuildId in runtime.

```C++
  auto path="/path/to/executable";
  const struct build_id_note *note = build_id_find_nhdr_by_name(path);
  if (!note) {
    return std::nullopt;
  }

  ElfW(Word) len = build_id_length(note);

  const uint8_t *build_id = build_id_data(note);

  std::vector<byte> result(build_id,build_id+len);
```
